common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost

development:
  <<: *common
  database: MatchTheCity-development

test:
  <<: *common
  database: MatchTheCity-test

production:
  <<: *common
  database: MatchTheCity-production
  username: MatchTheCity
  password: <%= ENV['MATCHTHECITY_DATABASE_PASSWORD'] %>
